# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registered',
            new_name='Users',
        ),
    ]
